# Generated by doctest: do not edit by hand
# Please edit file in R/r2.R

test_that("Doctest: r2_exact", {
  # Created from @doctest for `r2_exact`
  # Source file: R/r2.R
  # Source line: 28
  dat <- matrix(c(5, 5, 4, 6, 2, 7, 7, 4), ncol = 2, byrow = TRUE)
  expect_equal(r2_exact(dat, reference = c(0, 0)), 2.5941919191919194, tolerance = 1e-9)
  expect_equal(r2_exact(dat, reference = c(10, 10), maximise = TRUE), 2.5196969696969695, tolerance = 1e-9)
})
