# Generated by doctest: do not edit by hand
# Please edit file in R/vorob.R

test_that("Doctest: vorobT", {
  # Created from @doctest for `vorobT`
  # Source file: R/vorob.R
  # Source line: 20
  data(CPFs)
  res <- vorobT(CPFs, reference = c(2, 200))
  expect_equal(res$threshold, 44.140625)
  expect_equal(res$avg_hyp, 8943.3332)
  VD <- vorobDev(CPFs, VE = res$VE, reference = c(2, 200))
  expect_equal(VD, 3017.1299)
})

