ci:
  skip: [roxygenize] # Produces renv errors.
  autofix_prs: true
  autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci

repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9029  # enforce-version: v0.4.3.9029
    hooks:
      - id: parsable-R
      - id: no-browser-statement
      - id: no-print-statement
        exclude: '(do\.R)'
      - id: no-debug-statement
      - id: deps-in-desc
        args: [--root=r]
        files: '^r/R/'
        exclude: '(do\.R|vignettes/articles/.+\.Rmd)'
      - id: roxygenize
        args: [--root=r]
        files: '^r/(R|man)/'
        additional_dependencies:
          - Rdpack
          - doctest
          - matrixStats

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-symlinks
      - id: check-merge-conflict
        args: [ --assume-in-merge ]
      - id: check-added-large-files
        name: check-added-large-files (>200kb)
        args: ['--maxkb=200']
        exclude: 'python/tests/test_data/expected_output/.*'
      - id: check-added-large-files
        name: check-added-large-files in tests (>999kb)
        args: ['--maxkb=999']
        files: 'python/tests/test_data/expected_output/.*'
      - id: file-contents-sorter
        files: '\.Rbuildignore$|^bibkeys.txt$|WORDLIST'
      - id: end-of-file-fixer
        exclude: '(\.Rd|python/doc/source/reference/.*|test-doctest-.*)'

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.9.0
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.29.4
    hooks:
      - id: pyproject-fmt
        additional_dependencies: ["tox>=4.12.1"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.16.9
    hooks:
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
      # Run the linter.
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        types_or: [ python, pyi, jupyter ]
        require_serial: true

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.2
    hooks:
      - id: sphinx-lint

  - repo: local
    hooks:
    - id: enforced-pre-commit-hook-version
      name: Verify that enforced pre-commit hook version stays unchanged
      description: >-
        Enforce pre-commit hook versions in this file remains matching the
        corresponding request in the `# enforce-version` comment.
      # Using Python here because using
      # shell test does not always work in CIs:
      entry: >-
        python -c 'import pathlib, re, sys;
        pre_commit_config = pathlib.Path(sys.argv[1]);
        cfg_txt = pre_commit_config.read_text();
        new_cfg_txt = re.sub(
        r"(?P<spaces>\s+)rev:\s(?:\d+\.\d+\.\d+)\s{0,2}"
        r"#\senforce-version:\s(?P<enforced_version>\d+\.\d+\.\d+)"
        r"[ \t\f\v]*",
        r"\g<spaces>rev: \g<enforced_version>  "
        r"# enforce-version: \g<enforced_version>",
        cfg_txt,
        );
        cfg_txt != new_cfg_txt and
        pre_commit_config.write_text(new_cfg_txt)
        '
      pass_filenames: true
      language: system
      files: >-
        ^\.pre-commit-config\.ya?ml$
      types:
        - yaml
