#!/bin/sh

BIBFILES="authors.bib abbrev.bib journals.bib articles.bib biblio.bib crossref.bib"

for file in $BIBFILES; do
    # echo $file
    curl --silent https://raw.githubusercontent.com/iridia-ulb/references/master/${file} -o ${file}
done
tmpbib=$(mktemp --tmpdir tmpXXXXXXXXXX.bib)
keys=$(paste -d '#' -s bibkeys.txt | sed 's/#/\\\|/g')
bib2bib --warn-error --expand --expand-xrefs --no-comment --quiet --expand-xrefs $BIBFILES --remove pdf --remove alias -c "(\$key : \"$keys\")" -ob $tmpbib -oc /dev/null

# Workaround https://github.com/GeoBosh/rbibutils/issues/9
sed -i 's#\\slash #~/ #g' $tmpbib
sed -i 's#\\hspace{0pt}#{}{}{}#g' $tmpbib
# Work around broken URL:
sed -i 's%researchrepository.napier.ac.uk/id/eprint/3044%lopez-ibanez.eu/publications#LopezIbanezPhD%g' $tmpbib
comment='% DO NOT EDIT THIS FILE. It is auto-generated by "update_bib.sh".'
PYTHON_DOC_DIR="./python/doc/source"
echo $comment | cat --squeeze-blank - $tmpbib > r/inst/REFERENCES.bib
echo $comment | cat --squeeze-blank - $tmpbib > $PYTHON_DOC_DIR/REFERENCES.bib
rm -f $BIBFILES $tmpbib
