#!/bin/sh

BIBFILES="authors.bib abbrev.bib journals.bib articles.bib biblio.bib crossref.bib"

for file in $BIBFILES; do
    # echo $file
    curl --silent --show-error https://raw.githubusercontent.com/iridia-ulb/references/master/${file} -o ${file}
    if [ ! -s "${file}" ]; then
        echo "error: ${file} is empty!"
        exit 1
    fi
done
tmpbib=$(mktemp --tmpdir tmpXXXXXXXXXX.bib)
keys=$(paste -d '#' -s bibkeys.txt | sed 's/#/\\\|/g')
bib2bib --warn-error --expand --expand-xrefs --no-comment --expand-xrefs $BIBFILES --remove pdf --remove ids -c "(\$key : \"$keys\")" -ob $tmpbib -oc /dev/null
if [ ! -s "${tmpbib}" ]; then
    echo "error: ${tmpbib} is empty! keys:= $keys"
    exit 1
fi
# Workaround https://github.com/GeoBosh/rbibutils/issues/9
sed -i -e 's#\\slash #~/ #g' \
    -e 's#\\hspace{0pt}#{}{}{}#g' \
    -e 's%researchrepository.napier.ac.uk/id/eprint/3044%lopez-ibanez.eu/publications#LopezIbanezPhD%g' \
    $tmpbib
comment='% DO NOT EDIT THIS FILE. It is auto-generated by "update_bib.sh".'
echo $comment | cat --squeeze-blank - $tmpbib > r/inst/REFERENCES.bib
cp --force r/inst/REFERENCES.bib ./python/doc/source/REFERENCES.bib
rm -f $BIBFILES $tmpbib
