name: Build Dependencies(Win-ARM64)
description: "Setup LLVM for Win-ARM64 builds"
# https://github.com/numpy/numpy-release/blob/295d6a70a867972774ff05ae98d7a560a659e2b4/.github/windows_arm64_steps/action.yml

runs:
  using: "composite"
  steps:
    - name: Install LLVM with checksum verification
      shell: pwsh
      run: |
        Invoke-WebRequest https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.8/LLVM-21.1.8-woa64.exe -UseBasicParsing -OutFile LLVM-woa64.exe
        $expectedHash = "1a770a49460b73667c1750b79f90e7027ead468f966c5d30e180cae19f61d91e"
        $fileHash = (Get-FileHash -Path "LLVM-woa64.exe" -Algorithm SHA256).Hash
        if ($fileHash -ne $expectedHash) {
            Write-Error "Checksum verification failed. The downloaded file may be corrupted or tampered with."
            exit 1
        }
        Start-Process -FilePath ".\LLVM-woa64.exe" -ArgumentList "/S" -Wait
        echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "CC=clang-cl" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "CXX=clang-cl" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "LD=lld-link" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Confirm LLVM installation
      shell: pwsh
      run: |
        clang-cl --version
        lld-link --version
