# Useful to generate the R_phi low-discrepancy sequence:
# https://extremelearning.com.au/unreasonable-effectiveness-of-quasirandom-sequences/
# https://observablehq.com/@jrus/plastic-sequence
# https://www.shadertoy.com/view/4dtBWH
# See also: https://github.com/arvoelke/nengolib/pull/153

from sympy import symbols, solve, N
from mpmath import mp
import numpy as np
import re


# Set precision to 128 bits
mp.prec = 128


def eq(d):
    return x ** (d + 1) - x - 1


# Function to compute the real root numerically
def real_root(d):
    # Initial guess (a reasonable approximation)
    x0 = mp.mpf(1.5)
    # Solve using Newton's method
    return mp.findroot(lambda x: x ** (d + 1) - x - 1, x0, verify=True)


# Compute roots for d = 3 to 32
x = symbols("x", is_real=True, is_positive=True)
phi_d = {}

for d in [1, 2]:
    sol = solve(eq(d), x)
    sol = [s for s in sol if s.is_real and s.is_positive][0]
    phi_d[d] = N(sol, mp.dps).num

for d in range(3, 33):
    phi_d[d] = real_root(d)

inv_phi_d = {}
for d, phi in phi_d.items():
    inv_phi_d[d] = 1.0 / phi


# Recent versions of mpmpath support this already.
# See https://github.com/mpmath/mpmath/issues/345
def hex(a, prec=128):
    """
    Convert multiprecison float to hexadecimal representation with a defined precision
    """
    a2 = mp.mpmathify(a)
    if a2 == mp.mpf("0.0"):
        return "0.0"

    minus = False
    if a2 < 0:
        a2 = -a2
        minus = True
    e = mp.floor(mp.log(a2) / mp.log(mp.mpf("2.0")))
    a2 = a2 * mp.power(mp.mpf("2.0"), -e) - mp.mpf("1.0")
    if minus:
        retstr = "-0x1."
    else:
        retstr = "0x1."
    for l_i in range(prec):
        a2 = a2 * mp.mpf("16")
        b = int(a2)
        a2 = a2 - mp.mpf(b)
        retstr += "%.1x" % b

    retstr += "p%+.2d" % e
    retstr = re.sub("0+p", "p", retstr)
    return retstr


# Generate Python output
py_array = "# Generated by harmonious_seq.py\n"
py_array += "inv_phi_d = np.fromiter(map(float.fromhex, [\n"
for d, phi in inv_phi_d.items():
    py_array += f"    '{float(phi).hex()}', # d = {d}, value = {float(phi)}\n"
py_array += "]), dtype=float)\n"
print(py_array)


# Generate C array output
c_array = "// Generated by harmonious_seq.py\n"
c_array += "static const long double recip_phi_d[] = {\n"
for d, phi in inv_phi_d.items():
    c_array += f"    {hex(phi)}L, // d = {d}, value = {np.float128(phi)}\n"
c_array += "};\n"
print(c_array)
