# Useful to generate the R_phi low-discrepancy sequence:
# https://extremelearning.com.au/unreasonable-effectiveness-of-quasirandom-sequences/
# https://observablehq.com/@jrus/plastic-sequence
# https://www.shadertoy.com/view/4dtBWH
# See also: https://github.com/arvoelke/nengolib/pull/153

# Requires
# sympy >= 1.14.0
# mpmath>=1.4.1
from sympy import symbols, solve, N
from mpmath import mp
import numpy as np

# Set precision to 128 bits
mp.prec = 128


def eq(d):
    return x ** (d + 1) - x - 1


def real_root(d):
    # Initial guess (a reasonable approximation)
    x0 = mp.mpf(1.5)
    # Solve using Newton's method
    return mp.findroot(lambda x: x ** (d + 1) - x - 1, x0, verify=True)


# Compute roots for d = 1 to 31
x = symbols("x", is_real=True, is_positive=True)
phi_d = {}
for d in range(1, 11):
    sol = solve(eq(d), x)
    sol = [N(s, mp.dps) for s in sol]
    sol = [s for s in sol if s.is_real and s.is_positive]
    phi_d[d] = sol[0].num

# Beyond d > 10, it takes too long to solve symbolically, so we use mp.findroot()
for d in range(11, 32):
    phi_d[d] = real_root(d)

inv_phi_d = {}
for d, phi in phi_d.items():
    inv_phi_d[d] = mp.mpf(1.0) / phi


# Generate Python output
py_array = "# Generated by rphi_seq.py\n"
py_array += "inv_phi_d = np.fromiter(map(float.fromhex, [\n"
for d, phi in inv_phi_d.items():
    py_array += f"    '{phi:a}', # d = {d}, value = {float(phi)}\n"
py_array += "]), dtype=float)\n"
print(py_array)


# Generate C array output
c_array = "// Generated by rphi_seq.py\n"
c_array += "static const long double recip_phi_d[] = {\n"
for d, phi in inv_phi_d.items():
    c_array += f"    {phi:a}L, // d = {d}, value = {np.float128(phi)}\n"
c_array += "};\n"
print(c_array)
