from string import Template
import inspect

COMMON_PARAMS = {
    "points": """Array of numerical values, where each row gives the coordinates of a point in objective space.
    If the array is created by the :func:`read_datasets()` function, remove the last column.""",
    #
    "maximise": """Whether the objectives must be maximised instead of minimised.
    Either a single boolean value that applies to all objectives or a list of boolean values, with one value per objective.
    Also accepts a 1D numpy array with value 0/1 for each objective.""",
    #
    "ref_set": """Reference set as a matrix of numerical values. Must have the same number of columns as ``points``.""",
    #
    "ref_point": """Reference point as a 1D vector. Must be either a single value, which will be used for all coordinates,
    or the same length as a single point in ``points``.""",
    #
    "random_seed": """Either an integer to seed :func:`numpy.random.default_rng`, Numpy
    default random number generator (RNG) or an instance of a
    Numpy-compatible RNG. ``None`` uses the equivalent of a random seed, as in :func:`numpy.random.default_rng`.""",
    #
    "sets_of_points": """1D vector or list of values that gives the set of each row of ``points``.""",
    #
    "whv_rectangles": """Weighted rectangles that will bias the computation of the hypervolume.
    Maybe generated by :func:`eafdiff()` with  ``rectangles=True`` or by :func:`choose_eafdiff()`.""",
}


class DocSubstitute:
    def __init__(self):
        self.params = COMMON_PARAMS

    def __call__(self, func):
        if func.__doc__:
            try:
                func.__doc__ = Template(
                    inspect.cleandoc(func.__doc__)
                ).substitute(self.params)
            except KeyError as e:
                missing = e.args[0]
                raise RuntimeError(
                    f"Missing docstring substitution for '{missing}' in {func.__name__}"
                )
        return func
