import numpy as np

# FIXME: Implement also WFG hard type described here:
# https://www.sciencedirect.com/science/article/pii/S0305054816301538?via=ihub#bib26
# (code:
# https://github.com/renaudlr/moo-nondominated-sets/blob/master/wfgHardGenerator.R)

from ._docsubstitute import DocSubstitute
from ._moocore import any_dominated
from ._utils import is_integer_value


@DocSubstitute()
def generate_ndset(
    n: int,
    d: int,
    /,
    method: str,
    *,
    seed: int | np.random.Generator | None = None,
    integer: bool = False,
) -> np.ndarray:
    r"""Generate a random set of ``n`` mutually nondominated points of dimension ``d`` with the shape defined by ``method``.

    When ``integer=False`` (the default), the points are generated within the
    hypercube :math:`(0,1)^d` and can be scaled to another range using
    :func:`normalise`.  Otherwise, points are scaled to a non-negative integer
    range that keeps the points mutually nondominated.

    Parameters
    ----------
    n :
        Number of rows in the output.
    d :
        Number of columns in the output.
    method :
        Method used to generate the random nondominated set. See the Notes below for more details.
    seed :
        ${random_seed}
    integer:
        If ``True``, return integer-valued points.

    Returns
    -------
        A numeric matrix of size :math:`n \times d` containing nondominated points.

    Notes
    -----
    The available methods are:

    ``'simplex' | 'linear' | 'L'``
      Uniformly samples points on the standard simplex.
      This shape of nondominated set is also called ``'linear'`` in the literature :footcite:p:`LacKlaFon2017box`.

      The standard :math:`(d-1)`-simplex is defined by :math:`\{\vec{x}\in
      \mathbb{R}_+^d : \sum_{i=1}^d x_i = 1\}`.  Each point :math:`\vec{z} \in
      (0,1)^d \subset \mathbb{R}^d` is generated by sampling :math:`d`
      independent and identically distributed values :math:`(x_1,x_2, \dots,
      x_d)` from the exponential distribution, then dividing each value by the
      l1-norm of the vector, :math:`z_i = x_i / \sum_{i=1}^d x_i`
      :footcite:p:`RubMel1998simulation`.  Values sampled from the exponential
      distribution are guaranteed to be positive. Sampling from either the
      standard normal distribution :footcite:p:`GueFonPaq2021hv` or the uniform
      distribution :footcite:p:`LacKlaFon2017box` does not produce a uniform
      distribution when projected onto the simplex.

    ``'concave-sphere' | 'sphere' | 'C'``
      Uniformly samples points on the positive orthant of the hypersphere, which is concave when all objectives are minimised.

      Each point :math:`\vec{z} \in (0,1)^d \subset \mathbb{R}^d` is
      generated by sampling :math:`d` independent and identically distributed
      values :math:`\vec{x}=(x_1,x_2, \dots, x_d)` from the standard normal
      distribution, then dividing each value by the l2-norm of the vector,
      :math:`z_i = \frac{|x_i|}{\|\vec{x}\|_2}`
      :footcite:p:`Muller1959sphere`. The absolute value in the numerator ensures
      that points are sampled on the positive orthant of the hypersphere.
      Sampling from the uniform distribution :footcite:p:`LacKlaFon2017box` would
      not result in a uniform sampling when projected onto the surface of the
      hypersphere.

    ``'convex-sphere' | 'X'``
      Equivalent to ``1 - generate_ndset(..., method='concave-sphere')``, which is convex for minimisation problems. This shape has also been called *inverted convex* :footcite:p:`IshHeSha2019regular`. This sampling is uniform.

      It corresponds to translating points from the negative orthant of the hypersphere to the positive orthant. Thus, the sampling remains uniform.

    ``cliff-concave``
      Equivalent to generating a 2D set using ``method='concave-sphere'``, then
      generating the other :math:`d-2` columns uniformly at random within the
      unit hypercube :footcite:p:`EmmFon2011emo,GueFon2017hv4d`.
      This method does not make sense for ``d=2``.

      In the resulting set, the first two columns are mutually nondominated,
      i.e., no point can dominated another regardless of the other objectives.
      while the remaining :math:`d-2` columns do not provide any ordering.
      These sets are adversarial for algorithms that aim to exploit dominance
      structure.

      The dimensions that are generated at uniformly random should be
      chosen adversarially according to the algorithm being tested.
      Alternatively, the columns may be randomly shuffled using :func:`numpy.random.shuffle`.

    ``cliff-convex``
      Equivalent to ``1 - generate_ndset(..., method='cliff-concave')``.
      This method does not make sense for ``d=2``.


    ``'convex-simplex'``
      Equivalent to :code:`generate_ndset(..., method='simplex') ** 2`, which is convex for minimisation problems.
      Such a set cannot be obtained by any affine transformation of a subset of the hypersphere.  This sampling is *not* uniform.

      The corresponding surface is equivalent to a simplex curved towards the
      origin.  The generated points :math:`\vec{z} \in (0,1)^d \subset
      \mathbb{R}^d` satisfy :math:`\sum_{i=1}^d \sqrt{z_i} = 1`.  Although
      the sampling on the simplex is uniform, the transformed points are not.

    ``'concave-simplex'``
      Equivalent to ``1 - generate_ndset(..., method='convex-simplex')``, which is concave for minimisation problems. This shape has also been called *inverted concave* :footcite:p:`IshHeSha2019regular`.  This sampling is *not* uniform because ``method='convex-simplex'`` is not uniform.

    ``'inverted-simplex' | 'inverted-linear'``
      Equivalent to ``1 - generate_ndset(..., method='simplex')``. This sampling is uniform.


    Methods ``'inverted-simplex'``, ``'concave-simplex'`` and
    ``'convex-sphere'`` are translations of ``'simplex'``, ``'convex-simplex'``
    and ``'concave-sphere'``, respectively.  These translations have been
    called `inverted` shapes in the literature and have different properties
    than their `regular` counterparts :footcite:p:`IshHeSha2019regular`.


    References
    ----------
    .. footbibliography::

    Examples
    --------
    >>> moocore.generate_ndset(5, 3, "simplex", seed=42)
    array([[0.33742524, 0.32787894, 0.33469582],
           [0.15382676, 0.047522  , 0.79865124],
           [0.30561291, 0.67719985, 0.01718724],
           [0.47441115, 0.03192912, 0.49365973],
           [0.51684378, 0.11549762, 0.3676586 ]])
    >>> moocore.generate_ndset(5, 3, "simplex", seed=42, integer=True)
    array([[21, 20, 21],
           [ 9,  3, 51],
           [19, 43,  1],
           [30,  2, 31],
           [33,  7, 23]])
    >>> rng = np.random.default_rng(42)
    >>> moocore.generate_ndset(4, 2, "sphere", seed=rng)
    array([[0.28118049, 0.9596549 ],
           [0.62368072, 0.78167919],
           [0.83175713, 0.5551397 ],
           [0.37478326, 0.92711246]])
    >>> moocore.generate_ndset(3, 5, "convex-sphere", seed=rng)
    array([[0.98843533, 0.41282763, 0.39468745, 0.46462554, 0.95454935],
           [0.37787475, 0.74198125, 0.52575586, 0.79648617, 0.47079199],
           [0.47186748, 0.96998408, 0.88885902, 0.5906188 , 0.26499673]])
    >>> moocore.generate_ndset(4, 4, "convex-simplex", seed=rng)
    array([[0.19863075, 0.05673281, 0.02294823, 0.02710852],
           [0.00335494, 0.01822224, 0.26522868, 0.08531355],
           [0.22390087, 0.07032143, 0.00793081, 0.02978433],
           [0.08611603, 0.02473488, 0.02168134, 0.16162454]])
    >>> moocore.generate_ndset(3, 5, "cliff-convex", seed=42)
    array([[0.71881951, 0.0403451 , 0.2388603 , 0.21393569, 0.87188637],
           [0.37631928, 0.21832081, 0.54961406, 0.62920198, 0.07323501],
           [0.16824287, 0.4448603 , 0.35613488, 0.17723839, 0.5565858 ]])
    """
    if seed is None or is_integer_value(seed):
        seed = np.random.default_rng(seed)

    def _sample_simplex(n: int, d: int) -> np.ndarray:
        x = seed.exponential(size=(n, d))
        x /= x.sum(axis=1, keepdims=True)
        return x

    def _sample_sphere(n: int, d: int) -> np.ndarray:
        x = np.abs(seed.normal(size=(n, d)))
        x /= np.linalg.norm(x, axis=1, keepdims=True)
        return x

    def _sample_convex_sphere(n: int, d: int) -> np.ndarray:
        return 1.0 - _sample_sphere(n, d)

    def _sample_cliff_concave(n: int, d: int) -> np.ndarray:
        x = np.empty((n, d))
        x[:, :2] = _sample_sphere(n, 2)
        x[:, 2:] = seed.uniform(0, 1, size=(n, d - 2))
        return x

    def _sample_cliff_convex(n: int, d: int) -> np.ndarray:
        return 1.0 - _sample_cliff_concave(n, d)

    def _sample_convex_simplex(n: int, d: int) -> np.ndarray:
        return _sample_simplex(n, d) ** 2

    def _sample_inverted_simplex(n: int, d: int) -> np.ndarray:
        return 1.0 - _sample_simplex(n, d)

    def _sample_concave_simplex(n: int, d: int) -> np.ndarray:
        return 1.0 - _sample_convex_simplex(n, d)

    match method:
        case "simplex" | "linear" | "L":
            sample = _sample_simplex
        case "concave-sphere" | "sphere" | "C":
            sample = _sample_sphere
        case "convex-sphere" | "X":
            sample = _sample_convex_sphere
        case "cliff-concave" | "cliff-convex":
            if d <= 2:
                raise ValueError(
                    f"method='{method}' requires at least 3 dimensions"
                )
            sample = (
                _sample_cliff_concave
                if method == "cliff-concave"
                else _sample_cliff_convex
            )
        case "convex-simplex":
            sample = _sample_convex_simplex
        case "inverted-simplex" | "inverted-linear":
            sample = _sample_inverted_simplex
        case "concave-simplex":
            sample = _sample_concave_simplex
        case _:
            raise ValueError(f"unknown method={method}")

    while True:
        x = sample(n, d)
        # Due to rounding or bad luck, we may actually have dominated points.
        if not any_dominated(x):
            if not integer:
                return x
            break

    x *= 64
    while True:
        y = x.astype(int)
        if not any_dominated(y):
            return y
        x *= 2
