#!/bin/sh
rm -f  config.* confdefs.h tests/testthat/*.pdf \
       src/*.o src/*.so src/symbols.rds \
       inst/doc/*.blg inst/doc/*.bbl *-Ex.R

rm -rf autom4te.cache
find . -name '*.orig' -o -name '.Rhistory' -o -name '*.Rout' -print0 | xargs -0 rm -f
