name: spack-ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  spack-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Spack
        uses: actions/checkout@v4
        with:
          repository: spack/spack
          path: spack-tool

      - name: Set up Spack
        run: |
          . spack-tool/share/spack/setup-env.sh
          spack compiler find
          spack repo add $GITHUB_WORKSPACE/./spack
          spack env create ci
          spack env activate ci
          spack add py-moocore
          spack concretize -f
          spack install --fail-fast
        shell: bash